### Arrays

In [1]:
import numpy

def arrays(arr):
    return(numpy.array(arr[::-1], float))
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### Shape and Reshape

In [2]:
import numpy
print(numpy.array(input().split(), int).reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose and Flatten

In [3]:
import numpy

n, m = map(int, input().split())

storage = numpy.array([input().strip().split() for _ in range(n)], int)
print (storage.transpose())
print (storage.flatten())

2 2 
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### Concatenate

In [4]:
import numpy
P, N, M = map(int,input().split())
A = numpy.array([input().split() for _ in range(P)],int)
B = numpy.array([input().split() for _ in range(N)],int)
print(numpy.concatenate((A, B), axis = 0))

4 3 2
1 2 
1 2 
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### Zeros and Ones

In [5]:
import numpy
N = tuple(map(int, input().split()))
print(numpy.zeros(N, int))
print(numpy.ones(N, int))

3 3 3 
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### Eye and Identity

In [6]:
import numpy

numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Array Mathematics

In [7]:
import numpy

N, M = map(int, input().split())

A = numpy.array([list(map(int, input().split())) for n in range(N)])
B = numpy.array([list(map(int, input().split())) for n in range(N)])

print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)
print(A ** B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### Floor, Ceil and Rint 

In [9]:
import numpy

numpy.set_printoptions(sign=' ')

array = numpy.array(input().split(),float)

print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### Sum and Prod

In [10]:
import numpy

N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

2 2 
1 2 
3 4
24


### Min and Max 

In [12]:
import numpy

N, M = map(int, input().split())
storage = numpy.array([input().split() for _ in range(N)],int)
print(numpy.max(numpy.min(storage, axis=1), axis=0))

4 2 
2 5
3 7
1 3
4 0
3


### Mean, Var, and Std

In [13]:
import numpy

N, M = map(int, input().strip().split())

my_array = numpy.array([ input().strip().split() for _ in range(N) ], int)

print(numpy.mean(my_array, axis = 1))
print(numpy.var(my_array, axis = 0))
print(round(numpy.std(my_array, axis = None),11))

2 2 
1 2 
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### Dot and Cross

In [14]:
import numpy

n = int(input())
a = numpy.array([input().split() for _ in range(n)], int)
b = numpy.array([input().split() for _ in range(n)], int)
print(numpy.dot(a, b))

2 
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### Inner and Outer

In [15]:
import numpy

A = numpy.array(input().split(), int)
B = numpy.array(input().split(), int)
print(numpy.inner(A, B), numpy.outer(A, B), sep='\n')

0 1 
2 3
3
[[0 0]
 [2 3]]


### Polynomials

In [16]:
import numpy

poly = [float(x) for x in input().split()]
x = float(input())

print(numpy.polyval(poly, x))

1.1 2 3
0
3.0


### Linear Algebra

In [17]:
import numpy

import numpy
N = int(input())
A = numpy.array([input().split() for _ in range(N)], float)
print(round(numpy.linalg.det(A),2))

2
1.1 1.1
1.1 1.1
0.0


In [ ]:
2
1.1 1.1
1.1 1.1